Cast to float to prevent TypeError in PHP8
Method Product::getPriceWithoutReduct can return NULL in some versions
of thirty bees (and in some corner cases only). If ecotax is NULL as
well, it leads to expression: {null - null}, which raises error:

TypeError: Unsupported operand types: string - string